// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3rREJvwpMvMlNtJWQLzv3UVeydYo8D2U',
    appId: '1:269039297398:web:bae3d8ecbbcc91e4b45057',
    messagingSenderId: '269039297398',
    projectId: 'dairy-calculator-27b24',
    authDomain: 'dairy-calculator-27b24.firebaseapp.com',
    storageBucket: 'dairy-calculator-27b24.appspot.com',
    measurementId: 'G-J03RBMPXV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzxMnOCh7lUq0A6Q-b5eSB9OogOi-eeJw',
    appId: '1:269039297398:android:686fe6fcba1c0e48b45057',
    messagingSenderId: '269039297398',
    projectId: 'dairy-calculator-27b24',
    storageBucket: 'dairy-calculator-27b24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOAmgkTOhBkHUNYWWnJnn7BpwqENRwLs',
    appId: '1:269039297398:ios:2b380a1de99811a4b45057',
    messagingSenderId: '269039297398',
    projectId: 'dairy-calculator-27b24',
    storageBucket: 'dairy-calculator-27b24.appspot.com',
    iosBundleId: 'com.example.dairyCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOAmgkTOhBkHUNYWWnJnn7BpwqENRwLs',
    appId: '1:269039297398:ios:53c21e07e3338a30b45057',
    messagingSenderId: '269039297398',
    projectId: 'dairy-calculator-27b24',
    storageBucket: 'dairy-calculator-27b24.appspot.com',
    iosBundleId: 'com.example.dairyCalculator.RunnerTests',
  );
}
